# Generated by Django 5.2.8 on 2025-11-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_link', models.URLField(blank=True, null=True)),
                ('jd_link', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.department')),
            ],
        ),
        migrations.CreateModel(
            name='HiringRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(blank=True, unique=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('designation_status', models.CharField(choices=[('Existing Designation', 'Existing Designation'), ('New Designation', 'New Designation')], max_length=20)),
                ('hiring_designation', models.CharField(blank=True, max_length=200)),
                ('new_designation', models.CharField(blank=True, max_length=200)),
                ('joining_days', models.CharField(choices=[('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days'), ('120+ Days', '120+ Days')], max_length=20)),
                ('special_instructions', models.TextField()),
                ('hiring_status', models.CharField(default='Open', max_length=20)),
                ('cc_employees', models.ManyToManyField(blank=True, related_name='cc_in', to='hiring.employee')),
                ('hiring_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.department')),
                ('requisitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
            ],
        ),
    ]
