# Generated by Django 5.2.8 on 2025-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='jd_link',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='role_link',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='cc_employees',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='designation_status',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='hiring_dept',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='hiring_designation',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='hiring_status',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='joining_days',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='new_designation',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='requisitioner',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='special_instructions',
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
