# Generated by Django 5.2.8 on 2025-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_remove_department_email_remove_designation_jd_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequisition',
            name='cc_employees',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='days_well_thought',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='role_n_jd_exist',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='role_n_jd_good',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='role_n_jd_read',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
