# Generated by Django 5.2.8 on 2025-11-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_hiringrequisition_cc_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequisition',
            name='designation_status',
            field=models.CharField(default='Existing Designation', max_length=50),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='hiring_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='hiring.department'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='hiring_designation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='hiring_status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='joining_days',
            field=models.CharField(blank=True, default='30 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='new_designation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='requisitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='hiring.employee'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
