# Generated by Django 5.2.8 on 2025-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_department_department_type_department_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='jd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='role_document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='role_document_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
