# Generated by Django 5.2.8 on 2025-11-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_alter_designation_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
