# Generated by Django 5.2.8 on 2025-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequisition',
            name='jd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='role_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
