# Generated by Django 5.2.8 on 2025-12-08 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0009_hiringrequisition_jd_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='hiringrequisition',
            options={'ordering': ['-serial_no'], 'verbose_name': 'Hiring Requisition', 'verbose_name_plural': 'Hiring Requisitions'},
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Support', 'Support')], max_length=50, null=True, verbose_name='Department Type'),
        ),
        migrations.AlterField(
            model_name='department',
            name='group_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dept Group Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dept Head Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='page_link',
            field=models.URLField(blank=True, null=True, verbose_name='Dept Page Link (BO Internal Site)'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='days_well_thought',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='designation_status',
            field=models.CharField(choices=[('Existing Designation', 'Existing Designation'), ('New Designation', 'New Designation')], default='Existing Designation', max_length=50),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='hiring_dept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requisitions', to='hiring.department', verbose_name='Hiring Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='hiring_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='requisitioner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raised_requisitions', to='hiring.employee', verbose_name='Requisition Raised By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_exist',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_good',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_read',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
